jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
@@ -21,5 +21,6 @@ jobs:
      with:
        java-version: '11'
        distribution: 'adopt'
        architecture: x64
    - name: Build with Maven
      run: mvn -B package --file pom.xml